service: tasks-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  tasks-get:
    handler: tasks-get.handler
    events:
      - http:
          path: tasks
          method: get
          cors: true
  tasks-post:
    handler: tasks-post.handler
    events:
      - http:
          path: tasks
          method: post
          cors: true
